### ISSUE TITLE
Google Link not working

### ISSUE THREAD

**Issue by Punit-Choudhary** [Kundan-777/self-intro.github.io#1]
There is a space between google and .com that arises extra space in url, which causes **This Website can't be reached** issue.
link is present in **Bottom Bar**

**Comment by Punit-Choudhary** [comment]
Just remove the space from link.

**Comment by Kundan-777** [comment]
You can check now I remove the unwanted space .Now Google link is working

**Comment by Punit-Choudhary** [comment]
Ok fine
